#!/bin/bash

# CCMem Portal Stop Script
# Auto-generated by install-portal.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.json"
PID_FILE="$SCRIPT_DIR/portal.pid"

echo "🛑 Stopping CCMem Portal..."

# Check if config exists to get project info
if [ -f "$CONFIG_FILE" ]; then
    PROJECT_NAME=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG_FILE', 'utf8')).project.name" 2>/dev/null || echo "unknown")
    PROJECT_DISPLAY_NAME=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG_FILE', 'utf8')).project.displayName" 2>/dev/null || echo "Unknown Project")
    echo "🎯 Project: $PROJECT_DISPLAY_NAME ($PROJECT_NAME)"
fi

# Check if PID file exists
if [ ! -f "$PID_FILE" ]; then
    echo "⚠️  No PID file found. Portal may not be running."
    
    # Try to find and kill any running portal processes
    echo "🔍 Searching for running portal processes..."
    PORTAL_PIDS=$(pgrep -f "node.*server\.js" || echo "")
    
    if [ -n "$PORTAL_PIDS" ]; then
        echo "🎯 Found running portal processes: $PORTAL_PIDS"
        echo "$PORTAL_PIDS" | xargs kill -TERM 2>/dev/null || true
        sleep 2
        
        # Force kill if still running
        REMAINING_PIDS=$(pgrep -f "node.*server\.js" || echo "")
        if [ -n "$REMAINING_PIDS" ]; then
            echo "💀 Force killing remaining processes: $REMAINING_PIDS"
            echo "$REMAINING_PIDS" | xargs kill -KILL 2>/dev/null || true
        fi
        echo "✅ Cleanup completed"
    else
        echo "ℹ️  No portal processes found running"
    fi
    exit 0
fi

# Read PID and attempt graceful shutdown
SERVER_PID=$(cat "$PID_FILE")
echo "🆔 Found PID: $SERVER_PID"

# Check if process is actually running
if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "⚠️  Process $SERVER_PID is not running"
    rm -f "$PID_FILE"
    echo "🧹 Cleaned up stale PID file"
    exit 0
fi

# Graceful shutdown (SIGTERM)
echo "📤 Sending SIGTERM to process $SERVER_PID..."
if kill -TERM "$SERVER_PID" 2>/dev/null; then
    echo "⏳ Waiting for graceful shutdown..."
    
    # Wait up to 10 seconds for graceful shutdown
    for i in {1..10}; do
        if ! kill -0 "$SERVER_PID" 2>/dev/null; then
            echo "✅ Portal stopped gracefully"
            rm -f "$PID_FILE"
            exit 0
        fi
        sleep 1
    done
    
    # Force kill if graceful shutdown failed
    echo "⚠️  Graceful shutdown timed out. Force killing..."
    if kill -KILL "$SERVER_PID" 2>/dev/null; then
        echo "💀 Portal force stopped"
    else
        echo "❌ Failed to stop portal process"
    fi
else
    echo "❌ Failed to send SIGTERM to process $SERVER_PID"
fi

# Clean up PID file
rm -f "$PID_FILE"

echo "🧹 Cleanup completed"